import SpiderFarFromHomeMovieImage from "@/public/assets/images/spider-far-from-home.png";
import JokerMovieImage from "@/public/assets/images/joker.png";

export const getMovies = () => {
	return [
		{
			'id': 1,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': true,
			'isTrendingMovie': true,
		},
		{
			'id': 2,
			'image': JokerMovieImage,
			'name': 'Joker',
			'alt': 'joker',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': true,
			'isTrendingMovie': false,
		},
		{
			'id': 3,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': false,
			'isTrendingMovie': true,
		},
		{
			'id': 4,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': false,
			'isTrendingMovie': false,
		},
		{
			'id': 5,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': true,
			'isTrendingMovie': false,
		},
		{
			'id': 6,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': true,
			'isTrendingMovie': false,
		},
		{
			'id': 7,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': false,
			'isTrendingMovie': false,
		},
		{
			'id': 8,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': false,
			'isTrendingMovie': true,
		},
		{
			'id': 9,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': false,
			'isTrendingMovie': false,
		},
		{
			'id': 10,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': false,
			'isTrendingMovie': false,
		},
		{
			'id': 11,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': true,
			'isTrendingMovie': true,
		},
		{
			'id': 12,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': false,
			'isTrendingMovie': false,
		},
		{
			'id': 13,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'PG-13',
			'isUpcomingMovie': false,
			'isTrendingMovie': true,
		},
	];
}