import SpiderFarFromHomeMovieImage from "../../public/assets/images/spider-far-from-home.png";

export const getMovies = () => {
	return [
		{
			'id': 1,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'pg-13',
		},
		{
			'id': 2,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'pg-13',
		},
		{
			'id': 3,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'pg-13',
		},
		{
			'id': 4,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'pg-13',
		},
		{
			'id': 5,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'pg-13',
		},
		{
			'id': 6,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'pg-13',
		},
		{
			'id': 7,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'pg-13',
		},
		{
			'id': 8,
			'image': SpiderFarFromHomeMovieImage,
			'name': 'Spiderman: Far From Home',
			'alt': 'spiderman-far-from-home',
			'genre': 'Action',
			'releaseDate': '12 Dec 2022',
			'pg': 'pg-13',
		},
	];
}